[workspace]
members = [
    "crates/graphics_testing",
    "crates/shader_crate"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_arch, values("spirv"))'] }

[workspace.dependencies]
kiss3d = { version = "0.42.0", features = ["egui"] }
egui_plot = { version = "0.35.0" }
rapier3d-meshloader = { version = "0.13.0", features = ["stl", "collada", "wavefront"] }
rapier3d = "*"
glamx = { version = "0.3", features = ["bytemuck"] }
pollster = "0.4.0"
bytemuck = { version = "*", features = ["derive"]}
rand = "0.10.0"
include_dir = "*"
rfd = "0.17.2"
itertools = "0.14.0"
thiserror = "2.0.18"
# khal
khal = { git = "https://github.com/dimforge/khal.git", rev = "61ece42e149547539ef14e18c2dfa4fcf33967cf", features = ["derive", "cpu"] }
khal-builder = { git = "https://github.com/dimforge/khal.git", rev = "61ece42e149547539ef14e18c2dfa4fcf33967cf" }
khal-std = { git = "https://github.com/dimforge/khal.git", rev = "61ece42e149547539ef14e18c2dfa4fcf33967cf" }

# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16
[profile.dev.build-override]
opt-level = 3